service: firetail
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  pets:
    handler: app.pets
    events:
      - http:
          path: /
          method: get
